### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by 4ertus2** [powturbo/TurboTranspose#2]
Hi,

We are interested in use of your libraries in our project: https://github.com/ClickHouse/ClickHouse
Specifically in our column compression codecs: https://github.com/ClickHouse/ClickHouse/blob/master/src/Compression/ICompressionCodec.h

TurboPFor-Integer-Compression is interesting itself and Turbo-Transpose is interesting as optimisation of transpose functions here:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Compression/CompressionCodecT64.cpp#L168

The problem is your libraries are under GPL and we cannot use them directly. Could we find some solution to change license restrictions for the libraries?

**Comment by powturbo** [comment]
There are not plans to change the License of the powturbo software. A commercial license is available upon request.
